[package]
name = "lz-str"
version = "0.1.0"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
description = "A port of lz-string to Rust"
repository = "https://github.com/adumbidiot/lz-str-rs"
homepage = "https://github.com/adumbidiot/lz-str-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = [ "lz-string", "compression" ]
categories = [ "compression" ]

exclude = [
    "scripts/*",
    "js-test/*",
    ".github/*"
]

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
rustc-hash = { version = "1.1.0", optional = true }

# wasm-bindgen dependencies
js-sys = { version = "0.3.47", optional = true }
wasm-bindgen = { version = "0.2.70", optional = true }

[dev-dependencies]
rand = "0.8.3"
criterion = "0.3.4"

[features]
wasm-bindgen-support = [ "wasm-bindgen", "js-sys" ]
nightly = [ "criterion/real_blackbox" ]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"

[[bench]]
name = "compress"
harness = false

[[bench]]
name = "decompress"
harness = false

[package.metadata.wasm-pack.profile.profiling]
# wasm-opt kills debug info
wasm-opt = [ "-g", "-O3" ]

[package.metadata.wasm-pack.profile.profiling.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = [ "-O3" ]
