[package]
name = "lz-string"
version = "0.0.1"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"
description = "A port of the js library lz-string"
repository = "https://github.com/adumbidiot/lz-string-rs"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

[dev-dependencies]
rand = "0.7"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.48"

[profile.release]
lto = true