name: Bindings
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  WebAssembly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Build Package
        run: make build-wasm
        
      - name: Install Test Dependencies
        working-directory: js-test
        run: npm i
          
      - name: Run Tests
        working-directory: js-test
        run: npm test