name: Bindings
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  WebAssembly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Build Package
        run: make build-wasm
        
      - name: Install Test Dependencies
        working-directory: bindings/lz-str-wasm/binding-tests
        run: npm i
          
      - name: Run Tests
        working-directory: bindings/lz-str-wasm/binding-tests
        run: npm test
        
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Maturin
        run: pip install maturin
        
      - name: Build Wheel
        working-directory: bindings/lz-str-py
        run: maturin build --release