name: Rust
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasm-Pack
        uses: npm install -g wasm-pack 
      - name: Build lz-string-rs
        run: wasm-pack build --target nodejs -- --features wasm-bindgen-support
      - name: Install Test Dependencies
        run: |
        cd js-test
        npm i
      - name: Run tests
        run: |
        cd js-test
        npm test
