name: Rust
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy 
          override: true
      - name: RustFmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: '-- --check --color always'
      - name: Fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: '--tests --all --all-features -- -D warnings'
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --all --verbose --features wasm-bindgen-support
